# Generated by Django 3.2.15 on 2022-09-18 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=30, verbose_name='书名')),
                ('bpub_date', models.DateField(null=True, verbose_name='出版日期')),
                ('bread_count', models.IntegerField(default=0, verbose_name='阅读量')),
                ('bcomment_count', models.IntegerField(default=0, verbose_name='评论量')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否逻辑删除')),
            ],
            options={
                'db_table': 'books',
            },
        ),
        migrations.CreateModel(
            name='HeroInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hname', models.CharField(max_length=30, verbose_name='英雄名')),
                ('hgender', models.SmallIntegerField(choices=[(0, 'female'), (1, 'male')], default=0, verbose_name='性别')),
                ('hdescription', models.CharField(max_length=200, verbose_name='英雄描述')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否逻辑删除')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.bookinfo', verbose_name='所属图书')),
            ],
            options={
                'db_table': 'heros',
            },
        ),
    ]
